package com.google.ssmm.dao;

import com.google.ssmm.entity.FinancePoint;
import com.google.ssmm.entity.FinancePointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


public interface FinancePointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    long countByExample(FinancePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int deleteByExample(FinancePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int insert(FinancePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int insertSelective(FinancePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    List<FinancePoint> selectByExampleWithBLOBs(FinancePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    List<FinancePoint> selectByExample(FinancePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    FinancePoint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int updateByExampleSelective(@Param("record") FinancePoint record, @Param("example") FinancePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") FinancePoint record, @Param("example") FinancePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int updateByExample(@Param("record") FinancePoint record, @Param("example") FinancePointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int updateByPrimaryKeySelective(FinancePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(FinancePoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table finance_point
     *
     * @mbg.generated Sun Aug 06 20:57:22 CST 2023
     */
    int updateByPrimaryKey(FinancePoint record);
}